spring:
  threads:
    virtual:
      enabled: true
  application:
    name: spring-lifecycle
  main:
    allow-circular-references: true
  mvc:
    servlet:
      load-on-startup: 0

server:
  shutdown: graceful

logging:
  level:
    com.yangbingdong.spring.explore.lifecycle.autoconfigure: trace
    root: info

lifecycle:
  custom:
    name: Mike
    age: 18
