spring:
  threads:
    virtual:
      enabled: true
  application:
    name: spring-lifecycle

server:
  shutdown: graceful

logging:
  level:
    com.yangbingdong.spring.explore.lifecycle.autoconfigure: trace
    root: info

lifecycle:
  custom:
    name: Mike
    age: 18
