spring:
  threads:
    virtual:
      enabled: true
  application:
    name: spring-lifecycle
  main:
    allow-circular-references: true
  mvc:
    servlet:
      load-on-startup: 0
  cloud:
    nacos:
      discovery:
        enabled: false
      server-addr: 127.0.0.1:8848

server:
  shutdown: graceful

logging:
  level:
    com.yangbingdong.spring.explore.lifecycle.autoconfigure: trace
    root: info

lifecycle:
  custom:
    name: Mike
    age: 18
    block-shutdown: false
    graceful-deregister-nacos: true
